receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
exporters:
  # Data sources: traces, metrics, logs
  logging:
    loglevel: debug

  otlphttp:
    endpoint: http://otlp-backend:4319
    compression: none
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp, logging]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp, logging]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp, logging]
