receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
exporters:
  # Data sources: traces, metrics, logs
  logging:
    loglevel: debug

  # Data sources: traces
  jaeger:
    endpoint: "jaeger-otel-recipes:14250"
    tls:
      insecure: true
  # Data source: Metrics to our test server
  otlphttp:
    metrics_endpoint: http://test-metrics-server:4319/v1/metrics
    compression: none
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp, logging]
