version: "2.4"
services:

  otlp-backend:
    build:
      context: ./internal/otlp_backend
      dockerfile: Dockerfile
    ports:
      - "4319:4319" # OTLP HTTP receiver
    networks:
      - otel-recipes

  otel-collector-otel-recipes:
    image: otel/opentelemetry-collector-contrib:0.77.0
    command: ["--config=/etc/collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55670:55679" # zpages extension
    depends_on:
      - otlp-backend
    networks:
      - otel-recipes
networks:
  otel-recipes:
