receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://otlp-backend:4319
    compression: none
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp, debug]
