name: C# recipefile JSON schema validation
on:
  pull_request:
    paths:
      - 'src/csharp/recipefile.json'
      - '.github/workflows/jsonschema-validation-template.yml'
      - '.github/workflows/csharp-recipefile-validation.yml'
  workflow_dispatch:
jobs:
  jsonschema-tests:
    name: Test
    uses: joaopgrassi/otel-recipes/.github/workflows/jsonschema-validation-template.yml@main
    with:
      language: csharp
