name: Go Trace Console integration tests
on:
  pull_request:
    paths:
      - 'src/go/trace/console/**'
      - 'test/trace/**'
      - '.github/workflows/integration-template.yml'
      - '.github/workflows/go-trace-console.yml'
  workflow_dispatch:
jobs:
  integration-tests:
    name: Test
    uses: joaopgrassi/otel-recipes/.github/workflows/integration-template.yml@main
    with:
      sample_name: go.console.app
      sample_path: ./src/go/trace/console
      telemetry_signal: trace
