name: JavaScript recipefile validations
on:
  pull_request:
    paths:
      - 'otel-recipes-schema.json'
      - 'src/js/**/recipefile.json'
      - '.github/workflows/jsonschema-validation-template.yml'
      - '.github/workflows/recipefile-unique-validation-template.yml'
      - '.github/workflows/js-recipefile-validation.yml'
  workflow_dispatch:
jobs:
  jsonschema-tests:
    name: Validate recipefile against schema
    uses: joaopgrassi/otel-recipes/.github/workflows/jsonschema-validation-template.yml@main
    with:
      language: js

  sampleid-unique-tests:
    name: Validate sample ids
    uses: joaopgrassi/otel-recipes/.github/workflows/recipefile-unique-validation-template.yml@main
    with:
      language: js
