name: Publish OTLP Backend to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build/Push OTLP back-end docker image'
        working-directory: ./internal/otlp_backend
        run: |
          docker build . --no-cache --tag ghcr.io/joaopgrassi/otel-recipes/otlp-backend:latest
          docker push ghcr.io/joaopgrassi/otel-recipes/otlp-backend:latest
