name: Checks - Recipe dependencies

on:
  pull_request:
    paths:
      - "src/**"
      - "!src/site/**"

jobs:
  gen-matrix:
    name: Validate recipe file dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: diff
        uses: tj-actions/changed-files@v44
        with:
          json: true
          dir_names_exclude_current_dir: true

      - name: Get recipes with out-of-sync dependencies
        uses: actions/github-script@v7
        id: generator
        with:
          script: |
            const script = require('.github/scripts/validate-dependencies.js');
            return script('${{ steps.diff.outputs.all_changed_files }}', '${{ github.workspace }}');

      - name: Validate
        uses: actions/github-script@v7
        with:
          script: |
            const errors = JSON.parse('${{ steps.generator.outputs.result }}');
            if (errors.length === 0) {
              return;
            }
            console.log(errors);
            core.setFailed("Encountered recipe files with out-of-sync dependencies. See the above logs for more information.");
