name: Recipefile sample id unique validation reusable workflow
on:
  workflow_call:
    inputs:
      language:
        description: 'The name of the language folder containing the recipefile.json to be validated'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Test
        working-directory: ./test/sample-unique
        run: go test -v -language=${{ inputs.language }}
